### ISSUE TITLE
uppercase/lowercase error

### ISSUE THREAD

**Issue by dinuxdotde** [manfred-hofmann/Wortuhr_ESP32_mp3#1]
Hi, try to compile under linux, got this error:
In file included from /home/revilo/Arduino/WortUhr_ESP32/Wortuhr_esp32_mp3/Wortuhr_esp32_mp3.ino:100:0:
Ntp.h:10:21: fatal error: WiFiUDP.h: No such file or directory
compilation terminated.
exit status 1
WiFiUDP.h: No such file or directory

The correct is "WiFiUdp.h", not "WiFiUDP.h"

**Comment by manfred-hofmann** [comment]
Evtl. ein Linux-Problem. Danke für die Info.
