### ISSUE TITLE
yrno.cpp compile error: rnoclient -> setInsecure(); 

### ISSUE THREAD

**Issue by dinuxdotde** [manfred-hofmann/Wortuhr_ESP32_mp3#2]
Arduino: 1.8.16 (Linux), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

/home/revilo/Arduino/WortUhr_ESP32/Wortuhr_esp32_mp3/yrno.cpp: In member function 'uint16_t yrno::getOutdoorConditions(double, double)':
yrno.cpp:33:15: error: 'class WiFiClientSecure' has no member named 'setInsecure'
 yrnoclient -> setInsecure();                  //ohne Certificate Check
               ^
Multiple libraries were found for "SoftwareSerial.h"
 Used: /home/revilo/Arduino/libraries/EspSoftwareSerial
 Not used: /home/revilo/Arduino/libraries/SoftwareSerial
exit status 1
'class WiFiClientSecure' has no member named 'setInsecure'

**Comment by manfred-hofmann** [comment]
Bitte mal mit ESP32 Board Version 1.0.6 probieren.

**Comment by dinuxdotde** [comment]
Hallo, ja, damit hat es funktioniert. 
Vielen Dank.
K.A. welche Version ich installiert hatte.
